### ISSUE TITLE
Missing Panorama Files

### ISSUE THREAD

**Issue by pr0crustes** [Jochnickel/addon_template_butt#6]
Why aren't the files under the _content/dota_addons/addon_template_butt/panorama_ folder commited? The whole folder is missing, only the compiled files are available.
These are the .xml, .css and .js files that make the GUI.

**Comment by Jochnickel** [comment]
hm you could open the compiled files with notepad++

**Comment by Jochnickel** [comment]
you can find them in the panorama branch

**Comment by limjeck** [comment]
The compiled files are not exactly the same as the uncompiled ones, e.g. in xml layouts, the src property for importing styles is different. Also simply modifying the compiled files will cause problems, since I think the compiled version contains information like the length of the file or something, and writing more in the compiled files will truncate it. Also once the game is run once, any modifications doesn't seem to go through, even running it again, until you restart Dota. So yeah can we have the original panorama content please?

**Comment by Jochnickel** [comment]
agian :D 

> you can find them in the panorama branch

**Comment by Jochnickel** [comment]
again..

> you can find them in the panorama branch
